const actionTypes = {
  FETCH_REQUEST_POSTS: 'FETCH_REQUEST_POSTS',
  FETCH_SUCCESS_POSTS: 'FETCH_SUCCESS_POSTS',
  FETCH_ERROR_POSTS: 'FETCH_ERROR_POSTS',
  FETCH_REQUEST_IMAGES: 'FETCH_REQUEST_IMAGES',
  FETCH_SUCCESS_IMAGES: 'FETCH_SUCCESS_IMAGES',
  FETCH_ERROR_IMAGES: 'FETCH_ERROR_IMAGES',
};

export default actionTypes;
